name: Automated Individual Logs Workflow

on:
  schedule:
    - cron: '0 22 * * 2,4'  # This will run the workflow at 3PM UTC-7 (12am UTC)  
  workflow_dispatch:
    branches:
      - logs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to logs branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.AUTOMATED_LOG_TOKEN }}
        ref: 'logs'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyGithub
        pip install pytz

    - name: Run Automated Individual Logs Script
      env:
        AUTOMATED_LOG_TOKEN : ${{ secrets.AUTOMATED_LOG_TOKEN }}
        CLOCKIFY_API_KEY : ${{ secrets.CLOCKIFY_API_KEY }}
      run: python .github/workflows/scripts/automated-individual-logs.py

    - name: Commit and push changes
      run: |
        git config --global user.email "ghactions@gmail.com"
        git config --global user.name "Automated Individual Logs"
        git add -A
        git commit -m "Created Log templates: make sure to fill them out and review eachother's commits!"
        git push

  