# GH Action / Bash Script to send Discord Notifications when a PR review is requested

# First maps all of of the users to their Discord IDs, then loops through a Json array
# of the reviewers and adds them to a list of embedded discord mentions (the <@ID> format)
# The script then sends a notification to Discord with the reviewers mentioned with curl and
# the data is sent as Discord's embedded json message format
name: Discord Notification on PR Review Requested

on:
  pull_request:
    types: [review_requested]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      run: |
        declare -A map
        map["JoshFarwig"]="<@239921359847817216>"
        map["mahirr476"]="<@706320638301962291>"
        map["Bhavya290223"]="<@788404909107052546>"
        map["namekeptanonymous"]="<@312212189056466944>"

        REVIEWERS=$(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq -r '.[] | "- " + .login')
        MENTIONS=""
        for reviewer in $(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq -r '.[] | .login'); do
          MENTIONS+="${map[$reviewer]}\n"
        done

        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
               "username": "Github",
               "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
               "content": "'"${MENTIONS//$'\n'/'\n'}"'",
               "embeds": [{
                 "title": "Review Requested on Pull Request",
                 "url": "${{ github.event.pull_request.html_url }}",
                 "author": {
                   "name": "${{ github.event.pull_request.user.login }}",
                   "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                 },
                 "fields": [
                   {"name": "Title", "value": "${{ github.event.pull_request.title }}", "inline": false},
                   {"name": "Requested Reviewers", "value": "'"${REVIEWERS//$'\n'/'\n'}"'", "inline": false}
                 ]
               }]
             }' \
             ${{ secrets.PR_REVIEW_DISCORD_WEBHOOK_URL }}
